### ISSUE TITLE
Add a command to handle updating the roles of new guests. [Feature request]

### ISSUE THREAD

**Issue by franc-ist** [Oliy-Island/Glenn#21]
Similarly to how the resident voting command updates the roles of new residents if/when they are voted in, I think it would be nice to have a similar command without the voting to remove the Unverified role and add the Guest role to speed up approving new members to the island.

**Comment by jpbberry** [comment]
Waiting if @Oliyy approves, will implement!

**Comment by jpbberry** [comment]
I think a good solution to this issue would be to make it so when anyone is added to a role above them, the previous role is removed. I don't think a command for "guesting" a member is necessary. Unless there's a plan to allow citizens to let guests in (which imo would be best done with approving reactions on introductions).

**Comment by franc-ist** [comment]
I think the auto-removal of roles is probably the best idea here. If we let people approve guests there is potential for abuse, and gaming the "system".

**Comment by jpbberry** [comment]
Possibly, we'll see what oliy has to say.
Also oliy; should it do this with all roles? Example adding citizen will also remove resident etc.

**Comment by oliyy** [comment]
Yea, let's just make it so when a higher role is added the lower authority role is removed 

Guest added - Unverified removed 
Resident added - Guest removed
Citizen added - Resident removed

**Comment by jpbberry** [comment]
Got it! Working on it now.
